---
title: "Research Projects"
description: |
  Below are some projects that I've completed as a part of various courses.

output:
    distill::distill_article:
        toc: true
        toc_depth: 3
---
## Multiclass ASMA vs Targeted PGD Attack in Image Segmentation
[pdf](Projects/csc413project.pdf)

Coauthored with: [Johnson Vo](https://www.linkedin.com/in/johnson-vo-9b8735203/?originalSubdomain=ca) and [Jiabao (Jimbo) Xie](https://www.linkedin.com/in/jimbo-xie/)

"Deep learning networks have demonstrated high performance in a large variety of applications, such as image classification, speech recognition, and natural language processing. However, there exists a major vulnerability exploited by the use of adversarial attacks. An adversarial attack imputes  images by altering the input image very slightly, making it nearly undetectable to the naked eye, but results in a very different classification by the network. This paper explores the projected gradient descent (PGD) attack and the Adaptive Mask Segmentation Attack (ASMA) on the image segmentation DeepLabV3 model using two types of architectures: MobileNetV3 and ResNet50, It was found that PGD was very consistent in changing the segmentation to be its target while the generalization of ASMA to a multiclass target was not as effective. The existence of such attack however puts all of image classification deep learning networks in danger of exploitation."

## Predicting the 2025 Canadian Federal Election
[pdf](Projects/Assignment3.pdf)

Coauthored with: [Johnson Vo](https://www.linkedin.com/in/johnson-vo-9b8735203/?originalSubdomain=ca), [Vincent Chu](https://vincentcchu.github.io/), and Zhenning Guam

"Using two datasets, we’ve developed a method under a multilevel regression with post-stratification (MRP) approach in order to answer the question of which party will be the most likely to win the 2025 Canadian federal election." As a result of this data being gathered years ahead of the election, the same analysis on more recent data is the next step.

## Toronto Delay Subway Analysis
[pdf](Projects/A2FinalStats.pdf)

"So how do we decide where the subway system might need revisions? Given the complexity of the subway system, its believed the delays are inevitable, however any underlying patters in the subway delay, might indicate that there are factors affecting the delay that could be controlled." 

## Modeling Short Term Insider Trades
[Research Proposal](Projects/302Proposal.pdf) - [Methodology Flow Chart](Projects/LinRegFlowChart.pdf) - [Analysis](Projects/302FinalPaper.pdf)

This project was designed to attempt to model short changes in a stocks price after a prominent member of that company bought or sold shares of that stock. However, due to the nature of the project, a linear regression was a requirement and it ended up resulting in a poorly fitting model. As a result, no conclusion could be formed about the use of the used variables in developing a reliable trading strategy.




